

services:
  client:
    build:
      context: ./client
    ports:
      - "3001:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production