services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server